openapi: 3.1.0
info:
  title: New Relic Event Alerts Put API
  description: The New Relic Event API allows you to send custom event data to the New Relic platform via HTTP POST. Custom events submitted through this API can be queried and visualized using NRQL, making it suitable for tracking arbitrary business or application events. Each event is a JSON object with an eventType and any number of additional attribute key-value pairs.
  version: '1'
  contact:
    name: New Relic Support
    url: https://support.newrelic.com/
  termsOfService: https://newrelic.com/termsandconditions/terms
  x-last-validated: '2026-04-18'
servers:
- url: https://insights-collector.newrelic.com
  description: US Production
- url: https://insights-collector.eu01.nr-data.net
  description: EU Production
security:
- apiKey: []
tags:
- name: Put
paths:
  /applications/{id}.json:
    put:
      tags:
      - Put
      summary: New Relic Put Applications
      description: '<p>This API endpoint allows you to update certain parameters of your application.</p>


        <p>The input is expected to be in <strong>JSON or XML</strong> format in the body parameter of the PUT request. The exact

        schema is defined below. Any extra parameters passed in the body <strong>will be ignored</strong>.</p>


        <p>See our documentation for a discussion and simple example of

        <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/application-examples-v2/changing-alias-your-application-v2" target="_blank"> updating</a>

        an application.</p>


        '
      parameters:
      - name: id
        in: path
        description: Application ID
        required: true
        schema:
          type: integer
        example: 100
      requestBody:
        description: Application schema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
            examples:
              PutapplicationsidRequestExample:
                summary: Default putApplicationsId request
                x-microcks-default: true
                value:
                  application:
                    name: Example Title
          application/xml:
            schema:
              $ref: '#/components/schemas/Application'
            examples:
              PutapplicationsidRequestExample:
                summary: Default putApplicationsId request
                x-microcks-default: true
                value:
                  application:
                    name: Example Title
        required: true
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationResponse'
              examples:
                Putapplicationsid200Example:
                  summary: Default putApplicationsId 200 response
                  x-microcks-default: true
                  value:
                    application:
                      application_summary: {}
                      end_user_summary: {}
                      health_status: {}
                      id: {}
                      language: {}
                      last_reported_at: {}
                      links: {}
                      name: {}
                      reporting: {}
                      settings: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/ApplicationResponse'
              examples:
                Putapplicationsid200Example:
                  summary: Default putApplicationsId 200 response
                  x-microcks-default: true
                  value:
                    application:
                      application_summary: {}
                      end_user_summary: {}
                      health_status: {}
                      id: {}
                      language: {}
                      last_reported_at: {}
                      links: {}
                      name: {}
                      reporting: {}
                      settings: {}
      x-codegen-request-body-name: application
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: putApplicationsId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /alerts_conditions/{condition_id}.json:
    put:
      tags:
      - Put
      summary: New Relic Put Alerts Conditions
      description: 'ðŸ”¥ðŸ”¥ New users should use <a href="https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples/">these docs about managing alerts via NerdGraph.</a>


        <p>This API endpoint allows you to update APM Application and Key Transaction, Browser and Mobile application metric conditions for your alert policies.</p>


        <p><strong>Conditions for web transaction percentiles, or conditions targeting labels (dynamic targeting), are not available.</strong></p>


        <p>Note: <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/rest-api-key">Admin Userâ€™s API Key</a> is required.</p>


        <p>See Alerts Conditions &gt; Create for an explanation of the field values or the online

        documentation on <a href="https://docs.newrelic.com/docs/alerts/new-relic-alerts/rest-api-alerts/rest-api-calls-new-relic-alerts#conditions-update" target="_blank">updating conditions for policies</a>.</p>


        '
      parameters:
      - name: condition_id
        in: path
        description: Alerts condition to update
        required: true
        schema:
          type: integer
        example: 100
      requestBody:
        description: Condition schema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Condition'
            examples:
              PutalertsconditionsconditionidRequestExample:
                summary: Default putAlertsConditionsConditionId request
                x-microcks-default: true
                value:
                  condition:
                    condition_scope: example_value
                    enabled: true
                    entities:
                    - {}
                    gc_metric: example_value
                    metric: example_value
                    name: Example Title
                    terms:
                    - {}
                    type: example_value
                    violation_close_timer: 10
          application/xml:
            schema:
              $ref: '#/components/schemas/Condition'
            examples:
              PutalertsconditionsconditionidRequestExample:
                summary: Default putAlertsConditionsConditionId request
                x-microcks-default: true
                value:
                  condition:
                    condition_scope: example_value
                    enabled: true
                    entities:
                    - {}
                    gc_metric: example_value
                    metric: example_value
                    name: Example Title
                    terms:
                    - {}
                    type: example_value
                    violation_close_timer: 10
        required: true
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConditionResponse'
              examples:
                Putalertsconditionsconditionid200Example:
                  summary: Default putAlertsConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    condition:
                      condition_scope: {}
                      enabled: {}
                      entities: {}
                      gc_metric: {}
                      id: {}
                      metric: {}
                      name: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
                      user_defined: {}
                      violation_close_timer: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/ConditionResponse'
              examples:
                Putalertsconditionsconditionid200Example:
                  summary: Default putAlertsConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    condition:
                      condition_scope: {}
                      enabled: {}
                      entities: {}
                      gc_metric: {}
                      id: {}
                      metric: {}
                      name: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
                      user_defined: {}
                      violation_close_timer: {}
      x-codegen-request-body-name: condition
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: putAlertsConditionsConditionId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /alerts_entity_conditions/{entity_id}.json:
    put:
      tags:
      - Put
      summary: New Relic Put Alerts Entity Conditions Entity
      description: "ðŸ”¥ðŸ”¥ New users should use NRQL Alert Conditions, refer to <a href=\"https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples/\">these docs about managing alerts via NerdGraph.</a>\n\n<hr>\n\n<p>This API endpoint allows you to add an entity to a specified Alerts condition.</p>\n\n<p>Note: <a href=\"https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/rest-api-key\">Admin Userâ€™s API Key</a> is required.\n<br />\n  Entity type options (Synthetics is not yet supported):</p>\n\n<pre><code>BrowserApplication\n\nApplication\n\nMobileApplication\n\nServer\n\nKeyTransaction\n</code></pre>\n"
      parameters:
      - name: entity_id
        in: path
        description: Entity to add
        required: true
        schema:
          type: integer
        example: 100
      - name: entity_type
        in: query
        description: Entity Type
        required: true
        schema:
          type: string
        example: standard
      - name: condition_id
        in: query
        description: Alerts condition ID
        required: true
        schema:
          type: integer
        example: 100
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConditionResponse'
              examples:
                Putalertsentityconditionsentityid200Example:
                  summary: Default putAlertsEntityConditionsEntityId 200 response
                  x-microcks-default: true
                  value:
                    condition:
                      condition_scope: {}
                      enabled: {}
                      entities: {}
                      gc_metric: {}
                      id: {}
                      metric: {}
                      name: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
                      user_defined: {}
                      violation_close_timer: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/ConditionResponse'
              examples:
                Putalertsentityconditionsentityid200Example:
                  summary: Default putAlertsEntityConditionsEntityId 200 response
                  x-microcks-default: true
                  value:
                    condition:
                      condition_scope: {}
                      enabled: {}
                      entities: {}
                      gc_metric: {}
                      id: {}
                      metric: {}
                      name: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
                      user_defined: {}
                      violation_close_timer: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: putAlertsEntityConditionsEntityId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /alerts_external_service_conditions/{condition_id}.json:
    put:
      tags:
      - Put
      summary: New Relic Put Alerts External Service Conditions
      description: 'ðŸ”¥ðŸ”¥ New users should use NRQL Alert Conditions, refer to <a href="https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples/">these docs about managing alerts via NerdGraph.</a>


        <hr>


        <p>This API endpoint allows you to update external service conditions for your alert policies.</p>


        <p>Note: <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/rest-api-key">Admin Userâ€™s API Key</a> is required.</p>


        <p>See Alerts External Service Conditions &gt; Create for an explanation of the field values used in this command or the online documentation on

        <a href="https://docs.newrelic.com/docs/alerts/new-relic-alerts/rest-api-alerts/rest-api-calls-new-relic-alerts#ext-conditions-update" target="_blank">updating conditions for external services</a>.</p>

        '
      parameters:
      - name: condition_id
        in: path
        description: Alerts condition to update
        required: true
        schema:
          type: integer
        example: 100
      requestBody:
        description: Condition schema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExternalServiceCondition'
            examples:
              PutalertsexternalserviceconditionsconditionidRequestExample:
                summary: Default putAlertsExternalServiceConditionsConditionId request
                x-microcks-default: true
                value:
                  external_service_condition:
                    enabled: true
                    entities:
                    - {}
                    external_service_url: https://www.example.com
                    metric: example_value
                    name: Example Title
                    runbook_url: https://www.example.com
                    terms:
                    - {}
                    type: example_value
          application/xml:
            schema:
              $ref: '#/components/schemas/ExternalServiceCondition'
            examples:
              PutalertsexternalserviceconditionsconditionidRequestExample:
                summary: Default putAlertsExternalServiceConditionsConditionId request
                x-microcks-default: true
                value:
                  external_service_condition:
                    enabled: true
                    entities:
                    - {}
                    external_service_url: https://www.example.com
                    metric: example_value
                    name: Example Title
                    runbook_url: https://www.example.com
                    terms:
                    - {}
                    type: example_value
        required: true
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalServiceConditionResponse'
              examples:
                Putalertsexternalserviceconditionsconditionid200Example:
                  summary: Default putAlertsExternalServiceConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    external_service_condition:
                      enabled: {}
                      entities: {}
                      external_service_url: {}
                      id: {}
                      metric: {}
                      name: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/ExternalServiceConditionResponse'
              examples:
                Putalertsexternalserviceconditionsconditionid200Example:
                  summary: Default putAlertsExternalServiceConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    external_service_condition:
                      enabled: {}
                      entities: {}
                      external_service_url: {}
                      id: {}
                      metric: {}
                      name: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
      x-codegen-request-body-name: external_service_condition
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: putAlertsExternalServiceConditionsConditionId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /alerts_location_failure_conditions/{condition_id}.json:
    put:
      tags:
      - Put
      summary: New Relic Put Alerts Location Failure Conditions
      description: '<strong>ðŸ”¥ This endpoint will be deprecated after 2024/01 ðŸ”¥</strong> New users should use <a href="https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples/">these docs about managing alerts via NerdGraph.</a>


        <hr>


        <p>This API endpoint allows you to update the alerts location failure conditions for your Alerts policy.</p>

        '
      parameters:
      - name: condition_id
        in: path
        description: Alerts condition to update
        required: true
        schema:
          type: integer
        example: 100
      requestBody:
        description: Condition schema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Condition'
            examples:
              PutalertslocationfailureconditionsconditionidRequestExample:
                summary: Default putAlertsLocationFailureConditionsConditionId request
                x-microcks-default: true
                value:
                  condition:
                    condition_scope: example_value
                    enabled: true
                    entities:
                    - {}
                    gc_metric: example_value
                    metric: example_value
                    name: Example Title
                    terms:
                    - {}
                    type: example_value
                    violation_close_timer: 10
          application/xml:
            schema:
              $ref: '#/components/schemas/Condition'
            examples:
              PutalertslocationfailureconditionsconditionidRequestExample:
                summary: Default putAlertsLocationFailureConditionsConditionId request
                x-microcks-default: true
                value:
                  condition:
                    condition_scope: example_value
                    enabled: true
                    entities:
                    - {}
                    gc_metric: example_value
                    metric: example_value
                    name: Example Title
                    terms:
                    - {}
                    type: example_value
                    violation_close_timer: 10
        required: true
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConditionResponse'
              examples:
                Putalertslocationfailureconditionsconditionid200Example:
                  summary: Default putAlertsLocationFailureConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    condition:
                      condition_scope: {}
                      enabled: {}
                      entities: {}
                      gc_metric: {}
                      id: {}
                      metric: {}
                      name: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
                      user_defined: {}
                      violation_close_timer: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/ConditionResponse'
              examples:
                Putalertslocationfailureconditionsconditionid200Example:
                  summary: Default putAlertsLocationFailureConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    condition:
                      condition_scope: {}
                      enabled: {}
                      entities: {}
                      gc_metric: {}
                      id: {}
                      metric: {}
                      name: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
                      user_defined: {}
                      violation_close_timer: {}
      x-codegen-request-body-name: condition
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: putAlertsLocationFailureConditionsConditionId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /alerts_nrql_conditions/{condition_id}.json:
    put:
      tags:
      - Put
      summary: New Relic Put Alerts Nrql Conditions
      description: 'ðŸ”¥ðŸ”¥ New users should use <a href="https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples/">these docs about managing alerts via NerdGraph.</a>

        '
      parameters:
      - name: condition_id
        in: path
        description: Alerts condition to update
        required: true
        schema:
          type: integer
        example: 100
      requestBody:
        description: Condition schema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NrqlCondition'
            examples:
              PutalertsnrqlconditionsconditionidRequestExample:
                summary: Default putAlertsNrqlConditionsConditionId request
                x-microcks-default: true
                value:
                  nrql_condition:
                    enabled: true
                    expected_groups: 10
                    ignore_overlap: true
                    name: Example Title
                    runbook_url: https://www.example.com
                    terms:
                    - {}
                    value_function: example_value
          application/xml:
            schema:
              $ref: '#/components/schemas/NrqlCondition'
            examples:
              PutalertsnrqlconditionsconditionidRequestExample:
                summary: Default putAlertsNrqlConditionsConditionId request
                x-microcks-default: true
                value:
                  nrql_condition:
                    enabled: true
                    expected_groups: 10
                    ignore_overlap: true
                    name: Example Title
                    runbook_url: https://www.example.com
                    terms:
                    - {}
                    value_function: example_value
        required: true
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NrqlConditionResponse'
              examples:
                Putalertsnrqlconditionsconditionid200Example:
                  summary: Default putAlertsNrqlConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    nrql_condition:
                      enabled: {}
                      expected_groups: {}
                      id: {}
                      ignore_overlap: {}
                      name: {}
                      nrql: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
                      value_function: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/NrqlConditionResponse'
              examples:
                Putalertsnrqlconditionsconditionid200Example:
                  summary: Default putAlertsNrqlConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    nrql_condition:
                      enabled: {}
                      expected_groups: {}
                      id: {}
                      ignore_overlap: {}
                      name: {}
                      nrql: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
                      value_function: {}
      x-codegen-request-body-name: nrql_condition
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: putAlertsNrqlConditionsConditionId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /alerts_policies/{policy_id}.json:
    put:
      tags:
      - Put
      summary: New Relic Put Alerts Policies
      description: 'ðŸ”¥ðŸ”¥ New users should use <a href="https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples/">these docs about managing alerts via NerdGraph.</a>


        <p>This API endpoint updates Alerts policies associated with your New Relic account.</p>


        <p>Note: <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/rest-api-key">Admin Userâ€™s API Key</a> is required.</p>


        <p>See our documentation for a discussion on using the REST API for

        <a href="https://docs.newrelic.com/docs/alerts/new-relic-alerts/rest-api-alerts/rest-api-calls-new-relic-alerts#policies-update" target="_blank">updating policies</a>.</p>


        '
      parameters:
      - name: policy_id
        in: path
        description: Policy ID
        required: true
        schema:
          type: integer
        example: 100
      requestBody:
        description: Policy Schema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Policy'
            examples:
              PutalertspoliciespolicyidRequestExample:
                summary: Default putAlertsPoliciesPolicyId request
                x-microcks-default: true
                value:
                  policy:
                    incident_preference: example_value
                    name: Example Title
          application/xml:
            schema:
              $ref: '#/components/schemas/Policy'
            examples:
              PutalertspoliciespolicyidRequestExample:
                summary: Default putAlertsPoliciesPolicyId request
                x-microcks-default: true
                value:
                  policy:
                    incident_preference: example_value
                    name: Example Title
        required: true
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyResponse'
              examples:
                Putalertspoliciespolicyid200Example:
                  summary: Default putAlertsPoliciesPolicyId 200 response
                  x-microcks-default: true
                  value:
                    policy:
                      created_at: {}
                      id: {}
                      incident_preference: {}
                      name: {}
                      updated_at: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/PolicyResponse'
              examples:
                Putalertspoliciespolicyid200Example:
                  summary: Default putAlertsPoliciesPolicyId 200 response
                  x-microcks-default: true
                  value:
                    policy:
                      created_at: {}
                      id: {}
                      incident_preference: {}
                      name: {}
                      updated_at: {}
      x-codegen-request-body-name: policy
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: putAlertsPoliciesPolicyId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /alerts_policy_channels.json:
    put:
      tags:
      - Put
      summary: New Relic Put Alerts Policy Channels
      description: '<strong>ðŸ”¥ This endpoint will be deprecated after 2024/01 ðŸ”¥</strong> New users should use <a href="https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples/">these docs about managing alerts via NerdGraph.</a>


        <hr>


        <p>This API endpoint updates policy/channel associations.</p>


        <p>Note: <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/rest-api-key">Admin Userâ€™s API Key</a> is required.</p>


        <p>See our documentation for a discussion on <a href="https://docs.newrelic.com/docs/alerts/new-relic-alerts/rest-api-alerts/rest-api-calls-new-relic-alerts#policy-channels-update">updating notification channels with policies</a>.</p>

        '
      parameters:
      - name: policy_id
        in: query
        description: Policy ID
        required: true
        schema:
          type: integer
        example: 100
      - name: channel_ids
        in: query
        description: Channel IDs
        required: true
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
        example:
        - '500123'
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyChannelsResponse'
              examples:
                Putalertspolicychannels200Example:
                  summary: Default putAlertsPolicyChannels 200 response
                  x-microcks-default: true
                  value:
                    policy:
                      channel_ids: {}
                      id: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/PolicyChannelsResponse'
              examples:
                Putalertspolicychannels200Example:
                  summary: Default putAlertsPolicyChannels 200 response
                  x-microcks-default: true
                  value:
                    policy:
                      channel_ids: {}
                      id: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: putAlertsPolicyChannels
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /alerts_synthetics_conditions/{condition_id}.json:
    put:
      tags:
      - Put
      summary: New Relic Put Alerts Synthetics Conditions
      description: 'ðŸ”¥ðŸ”¥ New users should use NRQL Alert Conditions, refer to <a href="https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples/">these docs about managing alerts via NerdGraph.</a>


        <hr>


        <p>This API endpoint allows you to update Synthetics conditions for your alert policies.</p>


        <p>Note: <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/rest-api-key">Admin Userâ€™s API Key</a> is required.</p>


        <p>See our documentation for a discussion on <a href="https://docs.newrelic.com/docs/alerts/new-relic-alerts/rest-api-alerts/rest-api-calls-new-relic-alerts#synthetics-conditions-update" target="_blank">updating Synthetic conditions</a>.</p>


        <p>See Alerts Synthetics Conditions &gt; Create for an explanation of the field values used in this command.</p>

        '
      parameters:
      - name: condition_id
        in: path
        description: Alerts condition to update
        required: true
        schema:
          type: integer
        example: 100
      requestBody:
        description: Condition schema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SyntheticsCondition'
            examples:
              PutalertssyntheticsconditionsconditionidRequestExample:
                summary: Default putAlertsSyntheticsConditionsConditionId request
                x-microcks-default: true
                value:
                  synthetics_condition:
                    enabled: true
                    monitor_id: '500123'
                    name: Example Title
                    runbook_url: https://www.example.com
          application/xml:
            schema:
              $ref: '#/components/schemas/SyntheticsCondition'
            examples:
              PutalertssyntheticsconditionsconditionidRequestExample:
                summary: Default putAlertsSyntheticsConditionsConditionId request
                x-microcks-default: true
                value:
                  synthetics_condition:
                    enabled: true
                    monitor_id: '500123'
                    name: Example Title
                    runbook_url: https://www.example.com
        required: true
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyntheticsConditionResponse'
              examples:
                Putalertssyntheticsconditionsconditionid200Example:
                  summary: Default putAlertsSyntheticsConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    synthetics_condition:
                      enabled: {}
                      id: {}
                      monitor_id: {}
                      name: {}
                      runbook_url: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/SyntheticsConditionResponse'
              examples:
                Putalertssyntheticsconditionsconditionid200Example:
                  summary: Default putAlertsSyntheticsConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    synthetics_condition:
                      enabled: {}
                      id: {}
                      monitor_id: {}
                      name: {}
                      runbook_url: {}
      x-codegen-request-body-name: synthetics_condition
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: putAlertsSyntheticsConditionsConditionId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    ApplicationResponseType:
      type: object
      properties:
        application_summary:
          $ref: '#/components/schemas/AppSummaryResponse'
        end_user_summary:
          $ref: '#/components/schemas/EndUserSummaryResponse'
        health_status:
          type: string
          example: active
        id:
          type: integer
          example: 100
        language:
          type: string
          example: example_string
        last_reported_at:
          type: string
          format: date-time
          example: '2026-04-18T14:30:00Z'
        links:
          $ref: '#/components/schemas/ApplicationLinksResponse'
        name:
          type: string
          example: example-resource-01
        reporting:
          type: boolean
          example: true
        settings:
          $ref: '#/components/schemas/AppSettingsResponse'
    SyntheticsCondition:
      type: object
      properties:
        synthetics_condition:
          $ref: '#/components/schemas/SyntheticsConditionBody'
    NrqlConditionBody:
      type: object
      properties:
        enabled:
          type: boolean
          example: true
        expected_groups:
          type: integer
          example: 100
        ignore_overlap:
          type: boolean
          example: true
        name:
          type: string
          example: example-resource-01
        nrql:
          $ref: '#/components/schemas/NrqlBody'
        runbook_url:
          type: string
          example: https://portal.example.com/path/abc123
        terms:
          type: array
          items:
            $ref: '#/components/schemas/IJKTermsType'
          example:
          - duration: example_string
            operator: example_string
            priority: example_string
            threshold: example_string
            time_function: example_string
        value_function:
          type: string
          example: example_string
    PolicyChannelsResponseType:
      type: object
      properties:
        channel_ids:
          type: array
          items:
            type: integer
          example:
          - 100
        id:
          type: integer
          example: 100
    ApplicationBody:
      type: object
      properties:
        name:
          type: string
          example: example-resource-01
        settings:
          $ref: '#/components/schemas/AppSettingsBody'
    NrqlConditionResponse:
      type: object
      properties:
        nrql_condition:
          $ref: '#/components/schemas/NrqlConditionResponseType'
    AppSettingsResponse:
      type: object
      properties:
        app_apdex_threshold:
          type: number
          format: float
          example: 42.5
        enable_real_user_monitoring:
          type: boolean
          example: true
        end_user_apdex_threshold:
          type: number
          format: float
          example: 42.5
        use_server_side_config:
          type: boolean
          example: true
    PolicyChannelsResponse:
      type: object
      properties:
        policy:
          $ref: '#/components/schemas/PolicyChannelsResponseType'
    NrqlBody:
      type: object
      properties:
        query:
          type: string
          example: example_string
        since_value:
          type: string
          example: example_string
    PolicyResponse:
      type: object
      properties:
        policy:
          $ref: '#/components/schemas/PolicyResponseType'
    SyntheticsConditionResponseType:
      type: object
      properties:
        enabled:
          type: boolean
          example: true
        id:
          type: integer
          example: 100
        monitor_id:
          type: string
          example: '500123'
        name:
          type: string
          example: example-resource-01
        runbook_url:
          type: string
          example: https://portal.example.com/path/abc123
    Application:
      type: object
      properties:
        application:
          $ref: '#/components/schemas/ApplicationBody'
    ExternalServiceConditionResponseType:
      type: object
      properties:
        enabled:
          type: boolean
          example: true
        entities:
          type: array
          items:
            type: integer
          example:
          - 100
        external_service_url:
          type: string
          example: https://portal.example.com/path/abc123
        id:
          type: integer
          example: 100
        metric:
          type: string
          example: example_string
        name:
          type: string
          example: example-resource-01
        runbook_url:
          type: string
          example: https://portal.example.com/path/abc123
        terms:
          type: array
          items:
            $ref: '#/components/schemas/IJKTermsType'
          example:
          - duration: example_string
            operator: example_string
            priority: example_string
            threshold: example_string
            time_function: example_string
        type:
          type: string
          example: standard
    ConditionResponse:
      type: object
      properties:
        condition:
          $ref: '#/components/schemas/ConditionResponseType'
    IJKTermsType:
      type: object
      properties:
        duration:
          type: string
          example: example_string
        operator:
          type: string
          example: example_string
        priority:
          type: string
          example: example_string
        threshold:
          type: string
          example: example_string
        time_function:
          type: string
          example: example_string
    SyntheticsConditionBody:
      type: object
      properties:
        enabled:
          type: boolean
          example: true
        monitor_id:
          type: string
          example: '500123'
        name:
          type: string
          example: example-resource-01
        runbook_url:
          type: string
          example: https://portal.example.com/path/abc123
    AppSettingsBody:
      type: object
      properties:
        app_apdex_threshold:
          type: number
          format: float
          example: 42.5
        enable_real_user_monitoring:
          type: boolean
          example: true
        end_user_apdex_threshold:
          type: number
          format: float
          example: 42.5
    ConditionBody:
      type: object
      properties:
        condition_scope:
          type: string
          example: example_string
        enabled:
          type: boolean
          example: true
        entities:
          type: array
          items:
            type: integer
          example:
          - 100
        gc_metric:
          type: string
          example: example_string
        metric:
          type: string
          example: example_string
        name:
          type: string
          example: example-resource-01
        terms:
          type: array
          items:
            $ref: '#/components/schemas/IJKTermsType'
          example:
          - duration: example_string
            operator: example_string
            priority: example_string
            threshold: example_string
            time_function: example_string
        type:
          type: string
          example: standard
        user_defined:
          $ref: '#/components/schemas/UserDefinedConditionBody'
        violation_close_timer:
          type: integer
          example: 1718153645993
    AppSummaryResponse:
      type: object
      properties:
        apdex_score:
          type: number
          format: float
          example: 87.5
        apdex_target:
          type: number
          format: float
          example: 42.5
        concurrent_instance_count:
          type: integer
          example: 42
        error_rate:
          type: number
          format: float
          example: 12.3
        host_count:
          type: integer
          example: 42
        instance_count:
          type: integer
          example: 42
        response_time:
          type: number
          format: float
          example: 42.5
        throughput:
          type: number
          format: float
          example: 42.5
    ExternalServiceConditionResponse:
      type: object
      properties:
        external_service_condition:
          $ref: '#/components/schemas/ExternalServiceConditionResponseType'
    ExternalServiceConditionBody:
      type: object
      properties:
        enabled:
          type: boolean
          example: true
        entities:
          type: array
          items:
            type: integer
          example:
          - 100
        external_service_url:
          type: string
          example: https://portal.example.com/path/abc123
        metric:
          type: string
          example: example_string
        name:
          type: string
          example: example-resource-01
        runbook_url:
          type: string
          example: https://portal.example.com/path/abc123
        terms:
          type: array
          items:
            $ref: '#/components/schemas/IJKTermsType'
          example:
          - duration: example_string
            operator: example_string
            priority: example_string
            threshold: example_string
            time_function: example_string
        type:
          type: string
          example: standard
    PolicyBody:
      type: object
      properties:
        incident_preference:
          type: string
          example: '500123'
        name:
          type: string
          example: example-resource-01
    NrqlResponse:
      type: object
      properties:
        query:
          type: string
          example: example_string
        since_value:
          type: string
          example: example_string
    Condition:
      type: object
      properties:
        condition:
          $ref: '#/components/schemas/ConditionBody'
    NrqlCondition:
      type: object
      properties:
        nrql_condition:
          $ref: '#/components/schemas/NrqlConditionBody'
    SyntheticsConditionResponse:
      type: object
      properties:
        synthetics_condition:
          $ref: '#/components/schemas/SyntheticsConditionResponseType'
    UserDefinedConditionBody:
      type: object
      properties:
        metric:
          type: string
          example: example_string
        value_function:
          type: string
          example: example_string
    ExternalServiceCondition:
      type: object
      properties:
        external_service_condition:
          $ref: '#/components/schemas/ExternalServiceConditionBody'
    ApplicationResponse:
      type: object
      properties:
        application:
          $ref: '#/components/schemas/ApplicationResponseType'
    PolicyResponseType:
      type: object
      properties:
        created_at:
          type: integer
          example: 100
        id:
          type: integer
          example: 100
        incident_preference:
          type: string
          example: '500123'
        name:
          type: string
          example: example-resource-01
        updated_at:
          type: integer
          example: 100
    NrqlConditionResponseType:
      type: object
      properties:
        enabled:
          type: boolean
          example: true
        expected_groups:
          type: integer
          example: 100
        id:
          type: integer
          example: 100
        ignore_overlap:
          type: boolean
          example: true
        name:
          type: string
          example: example-resource-01
        nrql:
          $ref: '#/components/schemas/NrqlResponse'
        runbook_url:
          type: string
          example: https://portal.example.com/path/abc123
        terms:
          type: array
          items:
            $ref: '#/components/schemas/IJKTermsType'
          example:
          - duration: example_string
            operator: example_string
            priority: example_string
            threshold: example_string
            time_function: example_string
        type:
          type: string
          example: standard
        value_function:
          type: string
          example: example_string
    ApplicationLinksResponse:
      type: object
      properties:
        servers:
          type: array
          items:
            type: integer
          example:
          - 100
        application_hosts:
          type: array
          items:
            type: integer
          example:
          - 100
        application_instances:
          type: array
          items:
            type: integer
          example:
          - 100
    Policy:
      type: object
      properties:
        policy:
          $ref: '#/components/schemas/PolicyBody'
    EndUserSummaryResponse:
      type: object
      properties:
        apdex_score:
          type: number
          format: float
          example: 87.5
        apdex_target:
          type: number
          format: float
          example: 42.5
        response_time:
          type: number
          format: float
          example: 42.5
        throughput:
          type: number
          format: float
          example: 42.5
    UserDefinedConditionResponse:
      type: object
      properties:
        metric:
          type: string
          example: example_string
        value_function:
          type: string
          example: example_string
    ConditionResponseType:
      type: object
      properties:
        condition_scope:
          type: string
          example: example_string
        enabled:
          type: boolean
          example: true
        entities:
          type: array
          items:
            type: integer
          example:
          - 100
        gc_metric:
          type: string
          example: example_string
        id:
          type: integer
          example: 100
        metric:
          type: string
          example: example_string
        name:
          type: string
          example: example-resource-01
        runbook_url:
          type: string
          example: https://portal.example.com/path/abc123
        terms:
          type: array
          items:
            $ref: '#/components/schemas/IJKTermsType'
          example:
          - duration: example_string
            operator: example_string
            priority: example_string
            threshold: example_string
            time_function: example_string
        type:
          type: string
          example: standard
        user_defined:
          $ref: '#/components/schemas/UserDefinedConditionResponse'
        violation_close_timer:
          type: integer
          example: 1718153645993
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: Api-Key
      description: New Relic License Key or Ingest API Key
externalDocs:
  description: New Relic Event API Documentation
  url: https://docs.newrelic.com/docs/data-apis/ingest-apis/event-api/introduction-event-api/
