openapi: 3.1.0
info:
  title: New Relic Event Alerts Data API
  description: The New Relic Event API allows you to send custom event data to the New Relic platform via HTTP POST. Custom events submitted through this API can be queried and visualized using NRQL, making it suitable for tracking arbitrary business or application events. Each event is a JSON object with an eventType and any number of additional attribute key-value pairs.
  version: '1'
  contact:
    name: New Relic Support
    url: https://support.newrelic.com/
  termsOfService: https://newrelic.com/termsandconditions/terms
  x-last-validated: '2026-04-18'
servers:
- url: https://insights-collector.newrelic.com
  description: US Production
- url: https://insights-collector.eu01.nr-data.net
  description: EU Production
security:
- apiKey: []
tags:
- name: Data
paths:
  /applications/{application_id}/hosts/{host_id}/metrics/data.json:
    get:
      tags:
      - Data
      summary: New Relic Get Applications Hosts Host Metrics Data
      description: This API operation retrieves metric data for a specific host associated with a particular application in New Relic. By making a GET request to the endpoint with the application and host as path parameters, users can access detailed performance metrics and monitoring data for that specific host instance. The operation returns data in JSON format, which typically includes time-series metric values such as response times, throughput, error rates, and other performance indicators collected by New Relic's monitoring agents. Additional query parameters can be used to filter the metrics by name, specify time ranges, set data summarization options, and control the granularity of the returned data, making it useful for building custom dashboards, generating reports, or integrating New Relic monitoring data into external systems and workflows.
      parameters:
      - name: application_id
        in: path
        description: Application ID
        required: true
        schema:
          type: integer
        example: 100
      - name: host_id
        in: path
        description: Application Host ID
        required: true
        schema:
          type: integer
        example: 100
      - name: names
        in: query
        description: Retrieve specific metrics by name
        required: true
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
        example:
        - example_string
      - name: values
        in: query
        description: Retrieve specific metric values
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
        example:
        - example_string
      - name: from
        in: query
        description: Retrieve metrics after this time
        schema:
          type: string
          format: date-time
        example: '2026-04-18T14:30:00Z'
      - name: to
        in: query
        description: Retrieve metrics before this time
        schema:
          type: string
          format: date-time
        example: '2026-04-18T14:30:00Z'
      - name: period
        in: query
        description: Period of timeslices in seconds
        schema:
          type: integer
        example: 100
      - name: summarize
        in: query
        description: Summarize the data
        schema:
          type: boolean
        example: true
      - name: raw
        in: query
        description: Return unformatted raw values
        schema:
          type: boolean
        example: true
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricDataResponse'
              examples:
                Getapplicationsidhostshostidmetricsdata200Example:
                  summary: Default getApplicationsIdHostsHostIdMetricsData 200 response
                  x-microcks-default: true
                  value:
                    metric_data:
                      from: {}
                      metrics: {}
                      metrics_found: {}
                      metrics_not_found: {}
                      to: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/MetricDataResponse'
              examples:
                Getapplicationsidhostshostidmetricsdata200Example:
                  summary: Default getApplicationsIdHostsHostIdMetricsData 200 response
                  x-microcks-default: true
                  value:
                    metric_data:
                      from: {}
                      metrics: {}
                      metrics_found: {}
                      metrics_not_found: {}
                      to: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        WriteDescription: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: getApplicationsIdHostsHostIdMetricsData
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /applications/{application_id}/instances/{instance_id}/metrics/data.json:
    get:
      tags:
      - Data
      summary: New Relic Get Applications Instances Instance Metrics Data
      description: '<p>This API endpoint returns a list of values for each of the requested metrics. The list of available metrics

        can be returned using the Metric Name API endpoint.</p>


        <p>Metric data can be filtered by a number of parameters, including multiple names and values, and by time range.

        Metric names and values will be matched intelligently in the background.</p>


        <p>You can also retrieve a summarized data point across the entire time range selected by using the summarize

        parameter.</p>


        <p>See our documentation for a discussion on <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/pagination-api-output" target="_blank">

        output pagination</a>, <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/extracting-metric-data" target="_blank"> time range</a>

        related considerations, and for examples of <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/new-relic-rest-api-v2-getting-started#examples" target="_blank">requesting and using metric values</a>.</p>


        '
      parameters:
      - name: application_id
        in: path
        description: Application ID
        required: true
        schema:
          type: integer
        example: 100
      - name: instance_id
        in: path
        description: Application Instance ID
        required: true
        schema:
          type: integer
        example: 100
      - name: names
        in: query
        description: Retrieve specific metrics by name
        required: true
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
        example:
        - example_string
      - name: values
        in: query
        description: Retrieve specific metric values
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
        example:
        - example_string
      - name: from
        in: query
        description: Retrieve metrics after this time
        schema:
          type: string
          format: date-time
        example: '2026-04-18T14:30:00Z'
      - name: to
        in: query
        description: Retrieve metrics before this time
        schema:
          type: string
          format: date-time
        example: '2026-04-18T14:30:00Z'
      - name: period
        in: query
        description: Period of timeslices in seconds
        schema:
          type: integer
        example: 100
      - name: summarize
        in: query
        description: Summarize the data
        schema:
          type: boolean
        example: true
      - name: raw
        in: query
        description: Return unformatted raw values
        schema:
          type: boolean
        example: true
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricDataResponse'
              examples:
                Getapplicationsidinstancesinstanceidmetricsdata200Example:
                  summary: Default getApplicationsIdInstancesInstanceIdMetricsData 200 response
                  x-microcks-default: true
                  value:
                    metric_data:
                      from: {}
                      metrics: {}
                      metrics_found: {}
                      metrics_not_found: {}
                      to: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/MetricDataResponse'
              examples:
                Getapplicationsidinstancesinstanceidmetricsdata200Example:
                  summary: Default getApplicationsIdInstancesInstanceIdMetricsData 200 response
                  x-microcks-default: true
                  value:
                    metric_data:
                      from: {}
                      metrics: {}
                      metrics_found: {}
                      metrics_not_found: {}
                      to: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: getApplicationsIdInstancesInstanceIdMetricsData
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /applications/{application_id}/metrics/data.json:
    get:
      tags:
      - Data
      summary: New Relic Get Applications Metrics Data
      description: '<p>This API endpoint returns a list of values for each of the requested metrics. The list of available metrics

        can be returned using the Metric Name API endpoint.</p>


        <p>Metric data can be filtered by a number of parameters, including multiple names and values, and by time range.

        Metric names and values will be matched intelligently in the background.</p>


        <p>You can also retrieve a summarized data point across the entire time range selected by using the summarize

        parameter.</p>


        <p>See our documentation for a discussion on <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/pagination-api-output" target="_blank">

        output pagination</a>, <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/extracting-metric-data" target="_blank"> time range</a>

        related considerations, and for examples of <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/new-relic-rest-api-v2-getting-started#examples" target="_blank">requesting and using metric values</a>.</p>


        '
      parameters:
      - name: application_id
        in: path
        description: Application ID
        required: true
        schema:
          type: integer
        example: 100
      - name: names
        in: query
        description: Retrieve specific metrics by name
        required: true
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
        example:
        - example_string
      - name: values
        in: query
        description: Retrieve specific metric values
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
        example:
        - example_string
      - name: from
        in: query
        description: Retrieve metrics after this time
        schema:
          type: string
          format: date-time
        example: '2026-04-18T14:30:00Z'
      - name: to
        in: query
        description: Retrieve metrics before this time
        schema:
          type: string
          format: date-time
        example: '2026-04-18T14:30:00Z'
      - name: period
        in: query
        description: Period of timeslices in seconds
        schema:
          type: integer
        example: 100
      - name: summarize
        in: query
        description: Summarize the data
        schema:
          type: boolean
        example: true
      - name: raw
        in: query
        description: Return unformatted raw values
        schema:
          type: boolean
        example: true
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricDataResponse'
              examples:
                Getapplicationsidmetricsdata200Example:
                  summary: Default getApplicationsIdMetricsData 200 response
                  x-microcks-default: true
                  value:
                    metric_data:
                      from: {}
                      metrics: {}
                      metrics_found: {}
                      metrics_not_found: {}
                      to: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/MetricDataResponse'
              examples:
                Getapplicationsidmetricsdata200Example:
                  summary: Default getApplicationsIdMetricsData 200 response
                  x-microcks-default: true
                  value:
                    metric_data:
                      from: {}
                      metrics: {}
                      metrics_found: {}
                      metrics_not_found: {}
                      to: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: getApplicationsIdMetricsData
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /mobile_applications/{mobile_application_id}/metrics/data.json:
    get:
      tags:
      - Data
      summary: New Relic Get Mobile Applications Mobile Application Metrics Data
      description: '<p>This API endpoint returns a list of values for each of the requested metrics. The list of available metrics

        can be returned using the Metric Name API endpoint.</p>


        <p>Metric data can be filtered by a number of parameters, including multiple names and values, and by time range.

        Metric names and values will be matched intelligently in the background.</p>


        <p>You can also retrieve a summarized data point across the entire time range selected by using the summarize

        parameter.</p>


        <p>See our documentation for a discussion on <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/pagination-api-output" target="_blank">

        output pagination</a>, <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/extracting-metric-data" target="_blank"> time range</a>

        related considerations, and for examples of <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/new-relic-rest-api-v2-getting-started#examples" target="_blank">requesting and using metric values</a>.</p>


        '
      parameters:
      - name: mobile_application_id
        in: path
        description: Mobile application ID
        required: true
        schema:
          type: integer
        example: 100
      - name: names
        in: query
        description: Retrieve specific metrics by name
        required: true
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
        example:
        - example_string
      - name: values
        in: query
        description: Retrieve specific metric values
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
        example:
        - example_string
      - name: from
        in: query
        description: Retrieve metrics after this time
        schema:
          type: string
          format: date-time
        example: '2026-04-18T14:30:00Z'
      - name: to
        in: query
        description: Retrieve metrics before this time
        schema:
          type: string
          format: date-time
        example: '2026-04-18T14:30:00Z'
      - name: period
        in: query
        description: Period of timeslices in seconds
        schema:
          type: integer
        example: 100
      - name: summarize
        in: query
        description: Summarize the data
        schema:
          type: boolean
        example: true
      - name: raw
        in: query
        description: Return unformatted raw values
        schema:
          type: boolean
        example: true
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricDataResponse'
              examples:
                Getmobileapplicationsmobileapplicationidmetricsdata200Example:
                  summary: Default getMobileApplicationsMobileApplicationIdMetricsData 200 response
                  x-microcks-default: true
                  value:
                    metric_data:
                      from: {}
                      metrics: {}
                      metrics_found: {}
                      metrics_not_found: {}
                      to: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/MetricDataResponse'
              examples:
                Getmobileapplicationsmobileapplicationidmetricsdata200Example:
                  summary: Default getMobileApplicationsMobileApplicationIdMetricsData 200 response
                  x-microcks-default: true
                  value:
                    metric_data:
                      from: {}
                      metrics: {}
                      metrics_found: {}
                      metrics_not_found: {}
                      to: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: getMobileApplicationsMobileApplicationIdMetricsData
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    MetricDataResponseType:
      type: object
      properties:
        from:
          type: string
          format: date-time
          example: '2026-04-18T14:30:00Z'
        metrics:
          type: array
          items:
            $ref: '#/components/schemas/MetricResponse'
          example:
          - name: example-resource-01
            timeslices:
            - {}
        metrics_found:
          type: string
          example: example_string
        metrics_not_found:
          type: string
          example: example_string
        to:
          type: string
          format: date-time
          example: '2026-04-18T14:30:00Z'
    MetricResponse:
      type: object
      properties:
        name:
          type: string
          example: example-resource-01
        timeslices:
          type: array
          items:
            $ref: '#/components/schemas/TimesliceResponse'
          example:
          - from: '2026-04-18T14:30:00Z'
            to: '2026-04-18T14:30:00Z'
            values: {}
    MetricDataResponse:
      type: object
      properties:
        metric_data:
          $ref: '#/components/schemas/MetricDataResponseType'
    TimesliceResponse:
      type: object
      properties:
        from:
          type: string
          format: date-time
          example: '2026-04-18T14:30:00Z'
        to:
          type: string
          format: date-time
          example: '2026-04-18T14:30:00Z'
        values:
          type: object
          properties: {}
          example: {}
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: Api-Key
      description: New Relic License Key or Ingest API Key
externalDocs:
  description: New Relic Event API Documentation
  url: https://docs.newrelic.com/docs/data-apis/ingest-apis/event-api/introduction-event-api/
