openapi: 3.1.0
info:
  title: New Relic Event Alerts Delete API
  description: The New Relic Event API allows you to send custom event data to the New Relic platform via HTTP POST. Custom events submitted through this API can be queried and visualized using NRQL, making it suitable for tracking arbitrary business or application events. Each event is a JSON object with an eventType and any number of additional attribute key-value pairs.
  version: '1'
  contact:
    name: New Relic Support
    url: https://support.newrelic.com/
  termsOfService: https://newrelic.com/termsandconditions/terms
  x-last-validated: '2026-04-18'
servers:
- url: https://insights-collector.newrelic.com
  description: US Production
- url: https://insights-collector.eu01.nr-data.net
  description: EU Production
security:
- apiKey: []
tags:
- name: Delete
paths:
  /applications/{application_id}/deployments/{id}.json:
    delete:
      tags:
      - Delete
      summary: New Relic Delete Applications Deployments
      description: This API operation allows you to delete a specific deployment record from a New Relic application by making a DELETE request to the endpoint /applications/{application_id}/deployments/{id}.json, where {application_id} is the unique identifier of the application and {id} is the specific deployment record you want to remove. This is useful for removing incorrect or outdated deployment markers from your application's deployment history in New Relic, helping maintain accurate tracking of your application's release timeline and deployment events.
      parameters:
      - name: application_id
        in: path
        description: Application ID
        required: true
        schema:
          type: integer
        example: 100
      - name: id
        in: path
        description: Deployment ID
        required: true
        schema:
          type: integer
        example: 100
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeploymentResponse'
              examples:
                Deleteapplicationsiddeploymentsid200Example:
                  summary: Default deleteApplicationsIdDeploymentsId 200 response
                  x-microcks-default: true
                  value:
                    deployment:
                      changelog: {}
                      description: {}
                      id: {}
                      links: {}
                      revision: {}
                      timestamp: {}
                      user: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/DeploymentResponse'
              examples:
                Deleteapplicationsiddeploymentsid200Example:
                  summary: Default deleteApplicationsIdDeploymentsId 200 response
                  x-microcks-default: true
                  value:
                    deployment:
                      changelog: {}
                      description: {}
                      id: {}
                      links: {}
                      revision: {}
                      timestamp: {}
                      user: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        WriteDescription: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: deleteApplicationsIdDeploymentsId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /applications/{id}.json:
    delete:
      tags:
      - Delete
      summary: New Relic Delete Applications
      description: '<p>This API endpoint deletes an application and all of its reported data.</p>


        <p><strong>WARNING</strong>: Only applications that have stopped reporting can be deleted. This is an irreversible process

        which will delete all reported data for this application.</p>

        '
      parameters:
      - name: id
        in: path
        description: Application ID
        required: true
        schema:
          type: integer
        example: 100
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationResponse'
              examples:
                Deleteapplicationsid200Example:
                  summary: Default deleteApplicationsId 200 response
                  x-microcks-default: true
                  value:
                    application:
                      application_summary: {}
                      end_user_summary: {}
                      health_status: {}
                      id: {}
                      language: {}
                      last_reported_at: {}
                      links: {}
                      name: {}
                      reporting: {}
                      settings: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/ApplicationResponse'
              examples:
                Deleteapplicationsid200Example:
                  summary: Default deleteApplicationsId 200 response
                  x-microcks-default: true
                  value:
                    application:
                      application_summary: {}
                      end_user_summary: {}
                      health_status: {}
                      id: {}
                      language: {}
                      last_reported_at: {}
                      links: {}
                      name: {}
                      reporting: {}
                      settings: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: deleteApplicationsId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /alerts_channels/{channel_id}.json:
    delete:
      tags:
      - Delete
      summary: New Relic Delete Alerts Channels Channel
      description: '<strong>ðŸ”¥ This endpoint will be deprecated after 2024/01 ðŸ”¥</strong> New users should use <a href="https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples/">these docs about managing alerts via NerdGraph.</a>


        <p>This API endpoint deletes Alerts notification channels.</p>


        <p>Note: <code>User</code> notification channels cannot be deleted.</p>


        <p>Note: <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/rest-api-key">Admin Userâ€™s API Key</a> is required.</p>


        <p>See our documentation for a discussion on <a href="https://docs.newrelic.com/docs/alerts/new-relic-alerts/rest-api-alerts/rest-api-calls-new-relic-alerts#channels-delete">deleting notification channels</a>.</p>


        '
      parameters:
      - name: channel_id
        in: path
        description: Channel ID
        required: true
        schema:
          type: integer
        example: 100
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelResponse'
              examples:
                Deletealertschannelschannelid200Example:
                  summary: Default deleteAlertsChannelsChannelId 200 response
                  x-microcks-default: true
                  value:
                    channel:
                      configuration: {}
                      id: {}
                      links: {}
                      name: {}
                      type: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/ChannelResponse'
              examples:
                Deletealertschannelschannelid200Example:
                  summary: Default deleteAlertsChannelsChannelId 200 response
                  x-microcks-default: true
                  value:
                    channel:
                      configuration: {}
                      id: {}
                      links: {}
                      name: {}
                      type: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: deleteAlertsChannelsChannelId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /alerts_conditions/{condition_id}.json:
    delete:
      tags:
      - Delete
      summary: New Relic Delete Alerts Conditions
      description: 'ðŸ”¥ðŸ”¥ New users should use <a href="https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples/">these docs about managing alerts via NerdGraph.</a>


        <hr>


        <p>This API endpoint allows you to delete APM Application and Key Transaction, Browser and Mobile application metric conditions for your alert policies.</p>


        <p><strong>Conditions for web transaction percentiles, or conditions targeting labels (dynamic targeting), are not available.</strong></p>


        <p>Note: <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/rest-api-key">Admin Userâ€™s API Key</a> is required.</p>


        <p>See our documentation for a discussion on <a href="https://docs.newrelic.com/docs/alerts/new-relic-alerts/rest-api-alerts/rest-api-calls-new-relic-alerts#conditions-delete" target="_blank">deleting conditions</a>.</p>

        '
      parameters:
      - name: condition_id
        in: path
        description: Alerts condition ID
        required: true
        schema:
          type: integer
        example: 100
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConditionResponse'
              examples:
                Deletealertsconditionsconditionid200Example:
                  summary: Default deleteAlertsConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    condition:
                      condition_scope: {}
                      enabled: {}
                      entities: {}
                      gc_metric: {}
                      id: {}
                      metric: {}
                      name: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
                      user_defined: {}
                      violation_close_timer: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/ConditionResponse'
              examples:
                Deletealertsconditionsconditionid200Example:
                  summary: Default deleteAlertsConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    condition:
                      condition_scope: {}
                      enabled: {}
                      entities: {}
                      gc_metric: {}
                      id: {}
                      metric: {}
                      name: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
                      user_defined: {}
                      violation_close_timer: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: deleteAlertsConditionsConditionId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /alerts_entity_conditions/{entity_id}.json:
    delete:
      tags:
      - Delete
      summary: New Relic Delete Alerts Entity Conditions Entity
      description: 'ðŸ”¥ðŸ”¥ New users should use NRQL Alert Conditions, refer to <a href="https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples/">these docs about managing alerts via NerdGraph.</a>


        <hr>


        <p>This API endpoint allows you to disassociate an entity with a specified Alerts condition.</p>


        <p>Note: <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/rest-api-key">Admin Userâ€™s API Key</a> is required.</p>


        <p>Entity type options (Synthetics is not yet supported):</p>


        <pre><code>BrowserApplication


        Application


        MobileApplication


        Server


        KeyTransaction

        </code></pre>

        '
      parameters:
      - name: entity_id
        in: path
        description: Entity to remove
        required: true
        schema:
          type: integer
        example: 100
      - name: entity_type
        in: query
        description: Entity Type
        required: true
        schema:
          type: string
        example: standard
      - name: condition_id
        in: query
        description: Alerts condition ID
        required: true
        schema:
          type: integer
        example: 100
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConditionResponse'
              examples:
                Deletealertsentityconditionsentityid200Example:
                  summary: Default deleteAlertsEntityConditionsEntityId 200 response
                  x-microcks-default: true
                  value:
                    condition:
                      condition_scope: {}
                      enabled: {}
                      entities: {}
                      gc_metric: {}
                      id: {}
                      metric: {}
                      name: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
                      user_defined: {}
                      violation_close_timer: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/ConditionResponse'
              examples:
                Deletealertsentityconditionsentityid200Example:
                  summary: Default deleteAlertsEntityConditionsEntityId 200 response
                  x-microcks-default: true
                  value:
                    condition:
                      condition_scope: {}
                      enabled: {}
                      entities: {}
                      gc_metric: {}
                      id: {}
                      metric: {}
                      name: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
                      user_defined: {}
                      violation_close_timer: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: deleteAlertsEntityConditionsEntityId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /alerts_external_service_conditions/{condition_id}.json:
    delete:
      tags:
      - Delete
      summary: New Relic Delete Alerts External Service Conditions
      description: 'ðŸ”¥ðŸ”¥ New users should use NRQL Alert Conditions, refer to <a href="https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples/">these docs about managing alerts via NerdGraph.</a>


        <p>This API endpoint allows you to delete external service conditions associated with your alert policy.</p>


        <p>Note: <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/rest-api-key">Admin Userâ€™s API Key</a> is required.</p>


        <p>See our documentation for a discussion on <a href="https://docs.newrelic.com/docs/alerts/new-relic-alerts/rest-api-alerts/rest-api-calls-new-relic-alerts#ext-conditions-delete" target="_blank">deleting External services conditions</a>.</p>


        '
      parameters:
      - name: condition_id
        in: path
        description: Alerts condition ID
        required: true
        schema:
          type: integer
        example: 100
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExternalServiceConditionResponse'
              examples:
                Deletealertsexternalserviceconditionsconditionid200Example:
                  summary: Default deleteAlertsExternalServiceConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    external_service_condition:
                      enabled: {}
                      entities: {}
                      external_service_url: {}
                      id: {}
                      metric: {}
                      name: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/ExternalServiceConditionResponse'
              examples:
                Deletealertsexternalserviceconditionsconditionid200Example:
                  summary: Default deleteAlertsExternalServiceConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    external_service_condition:
                      enabled: {}
                      entities: {}
                      external_service_url: {}
                      id: {}
                      metric: {}
                      name: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: deleteAlertsExternalServiceConditionsConditionId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /alerts_location_failure_conditions/{condition_id}.json:
    delete:
      tags:
      - Delete
      summary: New Relic Delete Alerts Location Failure Conditions
      description: '<strong>ðŸ”¥ This endpoint will be deprecated after 2024/01 ðŸ”¥</strong> New users should use <a href="https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples/">these docs about managing alerts via NerdGraph.</a>


        <hr>


        <p>This API endpoint allows you to Delete the alerts location failure conditions for your Alerts policy.</p>

        '
      parameters:
      - name: condition_id
        in: path
        description: Alerts condition ID
        required: true
        schema:
          type: integer
        example: 100
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConditionResponse'
              examples:
                Deletealertslocationfailureconditionsconditionid200Example:
                  summary: Default deleteAlertsLocationFailureConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    condition:
                      condition_scope: {}
                      enabled: {}
                      entities: {}
                      gc_metric: {}
                      id: {}
                      metric: {}
                      name: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
                      user_defined: {}
                      violation_close_timer: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/ConditionResponse'
              examples:
                Deletealertslocationfailureconditionsconditionid200Example:
                  summary: Default deleteAlertsLocationFailureConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    condition:
                      condition_scope: {}
                      enabled: {}
                      entities: {}
                      gc_metric: {}
                      id: {}
                      metric: {}
                      name: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
                      user_defined: {}
                      violation_close_timer: {}
      x-codegen-request-body-name: condition
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: deleteAlertsLocationFailureConditionsConditionId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /alerts_nrql_conditions/{condition_id}.json:
    delete:
      tags:
      - Delete
      summary: New Relic Delete Alerts Nrql Conditions
      description: 'ðŸ”¥ðŸ”¥ New users should use <a href="https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples/">these docs about managing alerts via NerdGraph.</a>

        '
      parameters:
      - name: condition_id
        in: path
        description: Alerts condition ID
        required: true
        schema:
          type: integer
        example: 100
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NrqlConditionResponse'
              examples:
                Deletealertsnrqlconditionsconditionid200Example:
                  summary: Default deleteAlertsNrqlConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    nrql_condition:
                      enabled: {}
                      expected_groups: {}
                      id: {}
                      ignore_overlap: {}
                      name: {}
                      nrql: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
                      value_function: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/NrqlConditionResponse'
              examples:
                Deletealertsnrqlconditionsconditionid200Example:
                  summary: Default deleteAlertsNrqlConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    nrql_condition:
                      enabled: {}
                      expected_groups: {}
                      id: {}
                      ignore_overlap: {}
                      name: {}
                      nrql: {}
                      runbook_url: {}
                      terms: {}
                      type: {}
                      value_function: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: deleteAlertsNrqlConditionsConditionId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /alerts_policies/{policy_id}.json:
    delete:
      tags:
      - Delete
      summary: New Relic Delete Alerts Policies
      description: 'ðŸ”¥ðŸ”¥ New users should use <a href="https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples/">these docs about managing alerts via NerdGraph.</a>


        <p>This API endpoint deletes Alerts policies associated with your New Relic account.</p>


        <p>Note: <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/rest-api-key">Admin Userâ€™s API Key</a> is required.</p>


        <p>See our documentation for a discussion on using the REST API for

        <a href="https://docs.newrelic.com/docs/alerts/new-relic-alerts/rest-api-alerts/rest-api-calls-new-relic-alerts#policies-delete" target="_blank">deleting policies</a>.</p>


        '
      parameters:
      - name: policy_id
        in: path
        description: Policy ID
        required: true
        schema:
          type: integer
        example: 100
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyResponse'
              examples:
                Deletealertspoliciespolicyid200Example:
                  summary: Default deleteAlertsPoliciesPolicyId 200 response
                  x-microcks-default: true
                  value:
                    policy:
                      created_at: {}
                      id: {}
                      incident_preference: {}
                      name: {}
                      updated_at: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/PolicyResponse'
              examples:
                Deletealertspoliciespolicyid200Example:
                  summary: Default deleteAlertsPoliciesPolicyId 200 response
                  x-microcks-default: true
                  value:
                    policy:
                      created_at: {}
                      id: {}
                      incident_preference: {}
                      name: {}
                      updated_at: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: deleteAlertsPoliciesPolicyId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /alerts_policy_channels.json:
    delete:
      tags:
      - Delete
      summary: New Relic Delete Alerts Policy Channels
      description: '<strong>ðŸ”¥ This endpoint will be deprecated after 2024/01 ðŸ”¥</strong> New users should use <a href="https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples/">these docs about managing alerts via NerdGraph.</a>


        <hr>


        <p>This API endpoint deletes Alerts policy/channel associations.</p>


        <p>Note: <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/rest-api-key">Admin Userâ€™s API Key</a> is required.</p>


        <p>See our documentation for a discussion on <a href="https://docs.newrelic.com/docs/alerts/new-relic-alerts/rest-api-alerts/rest-api-calls-new-relic-alerts#policy-channels-delete">deleting notification channels with policies</a>.</p>

        '
      parameters:
      - name: policy_id
        in: query
        description: Policy ID
        required: true
        schema:
          type: integer
        example: 100
      - name: channel_id
        in: query
        description: Channel ID
        required: true
        schema:
          type: integer
        example: 100
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelResponse'
              examples:
                Deletealertspolicychannels200Example:
                  summary: Default deleteAlertsPolicyChannels 200 response
                  x-microcks-default: true
                  value:
                    channel:
                      configuration: {}
                      id: {}
                      links: {}
                      name: {}
                      type: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/ChannelResponse'
              examples:
                Deletealertspolicychannels200Example:
                  summary: Default deleteAlertsPolicyChannels 200 response
                  x-microcks-default: true
                  value:
                    channel:
                      configuration: {}
                      id: {}
                      links: {}
                      name: {}
                      type: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: deleteAlertsPolicyChannels
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /alerts_synthetics_conditions/{condition_id}.json:
    delete:
      tags:
      - Delete
      summary: New Relic Delete Alerts Synthetics Conditions
      description: 'ðŸ”¥ðŸ”¥ New users should use NRQL Alert Conditions, refer to <a href="https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples/">these docs about managing alerts via NerdGraph.</a>


        <p>This API endpoint allows you to delete Synthetics conditions associated with your alert policy.</p>


        <p>Note: <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/rest-api-key">Admin Userâ€™s API Key</a> is required.</p>


        <p>See our documentation for a discussion on <a href="https://docs.newrelic.com/docs/alerts/new-relic-alerts/rest-api-alerts/rest-api-calls-new-relic-alerts#synthetics-conditions-delete" target="_blank">deleting Synthetic conditions</a>.</p>


        '
      parameters:
      - name: condition_id
        in: path
        description: Alerts condition ID
        required: true
        schema:
          type: integer
        example: 100
      responses:
        '200':
          description: No response was specified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyntheticsConditionResponse'
              examples:
                Deletealertssyntheticsconditionsconditionid200Example:
                  summary: Default deleteAlertsSyntheticsConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    synthetics_condition:
                      enabled: {}
                      id: {}
                      monitor_id: {}
                      name: {}
                      runbook_url: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/SyntheticsConditionResponse'
              examples:
                Deletealertssyntheticsconditionsconditionid200Example:
                  summary: Default deleteAlertsSyntheticsConditionsConditionId 200 response
                  x-microcks-default: true
                  value:
                    synthetics_condition:
                      enabled: {}
                      id: {}
                      monitor_id: {}
                      name: {}
                      runbook_url: {}
      x-api-evangelist-processing:
        PascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        GenerateOperationSummariesFromPath: true
        ChooseTags: true
      operationId: deleteAlertsSyntheticsConditionsConditionId
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    ApplicationResponseType:
      type: object
      properties:
        application_summary:
          $ref: '#/components/schemas/AppSummaryResponse'
        end_user_summary:
          $ref: '#/components/schemas/EndUserSummaryResponse'
        health_status:
          type: string
          example: active
        id:
          type: integer
          example: 100
        language:
          type: string
          example: example_string
        last_reported_at:
          type: string
          format: date-time
          example: '2026-04-18T14:30:00Z'
        links:
          $ref: '#/components/schemas/ApplicationLinksResponse'
        name:
          type: string
          example: example-resource-01
        reporting:
          type: boolean
          example: true
        settings:
          $ref: '#/components/schemas/AppSettingsResponse'
    NrqlConditionResponse:
      type: object
      properties:
        nrql_condition:
          $ref: '#/components/schemas/NrqlConditionResponseType'
    AppSettingsResponse:
      type: object
      properties:
        app_apdex_threshold:
          type: number
          format: float
          example: 42.5
        enable_real_user_monitoring:
          type: boolean
          example: true
        end_user_apdex_threshold:
          type: number
          format: float
          example: 42.5
        use_server_side_config:
          type: boolean
          example: true
    DeploymentLinksResponse:
      type: object
      properties:
        application:
          type: integer
          example: 100
    PolicyResponse:
      type: object
      properties:
        policy:
          $ref: '#/components/schemas/PolicyResponseType'
    ChannelResponseType:
      type: object
      properties:
        configuration:
          type: object
          properties: {}
          example: {}
        id:
          type: integer
          example: 100
        links:
          $ref: '#/components/schemas/ChannelLinksResponse'
        name:
          type: string
          example: example-resource-01
        type:
          type: string
          example: standard
    SyntheticsConditionResponseType:
      type: object
      properties:
        enabled:
          type: boolean
          example: true
        id:
          type: integer
          example: 100
        monitor_id:
          type: string
          example: '500123'
        name:
          type: string
          example: example-resource-01
        runbook_url:
          type: string
          example: https://portal.example.com/path/abc123
    ExternalServiceConditionResponseType:
      type: object
      properties:
        enabled:
          type: boolean
          example: true
        entities:
          type: array
          items:
            type: integer
          example:
          - 100
        external_service_url:
          type: string
          example: https://portal.example.com/path/abc123
        id:
          type: integer
          example: 100
        metric:
          type: string
          example: example_string
        name:
          type: string
          example: example-resource-01
        runbook_url:
          type: string
          example: https://portal.example.com/path/abc123
        terms:
          type: array
          items:
            $ref: '#/components/schemas/IJKTermsType'
          example:
          - duration: example_string
            operator: example_string
            priority: example_string
            threshold: example_string
            time_function: example_string
        type:
          type: string
          example: standard
    ConditionResponse:
      type: object
      properties:
        condition:
          $ref: '#/components/schemas/ConditionResponseType'
    IJKTermsType:
      type: object
      properties:
        duration:
          type: string
          example: example_string
        operator:
          type: string
          example: example_string
        priority:
          type: string
          example: example_string
        threshold:
          type: string
          example: example_string
        time_function:
          type: string
          example: example_string
    ExternalServiceConditionResponse:
      type: object
      properties:
        external_service_condition:
          $ref: '#/components/schemas/ExternalServiceConditionResponseType'
    AppSummaryResponse:
      type: object
      properties:
        apdex_score:
          type: number
          format: float
          example: 87.5
        apdex_target:
          type: number
          format: float
          example: 42.5
        concurrent_instance_count:
          type: integer
          example: 42
        error_rate:
          type: number
          format: float
          example: 12.3
        host_count:
          type: integer
          example: 42
        instance_count:
          type: integer
          example: 42
        response_time:
          type: number
          format: float
          example: 42.5
        throughput:
          type: number
          format: float
          example: 42.5
    DeploymentResponse:
      type: object
      properties:
        deployment:
          $ref: '#/components/schemas/DeploymentResponseType'
    NrqlResponse:
      type: object
      properties:
        query:
          type: string
          example: example_string
        since_value:
          type: string
          example: example_string
    ChannelResponse:
      type: object
      properties:
        channel:
          $ref: '#/components/schemas/ChannelResponseType'
    SyntheticsConditionResponse:
      type: object
      properties:
        synthetics_condition:
          $ref: '#/components/schemas/SyntheticsConditionResponseType'
    ChannelLinksResponse:
      type: object
      properties:
        policy_ids:
          type: array
          items:
            type: integer
          example:
          - 100
    ApplicationResponse:
      type: object
      properties:
        application:
          $ref: '#/components/schemas/ApplicationResponseType'
    PolicyResponseType:
      type: object
      properties:
        created_at:
          type: integer
          example: 100
        id:
          type: integer
          example: 100
        incident_preference:
          type: string
          example: '500123'
        name:
          type: string
          example: example-resource-01
        updated_at:
          type: integer
          example: 100
    NrqlConditionResponseType:
      type: object
      properties:
        enabled:
          type: boolean
          example: true
        expected_groups:
          type: integer
          example: 100
        id:
          type: integer
          example: 100
        ignore_overlap:
          type: boolean
          example: true
        name:
          type: string
          example: example-resource-01
        nrql:
          $ref: '#/components/schemas/NrqlResponse'
        runbook_url:
          type: string
          example: https://portal.example.com/path/abc123
        terms:
          type: array
          items:
            $ref: '#/components/schemas/IJKTermsType'
          example:
          - duration: example_string
            operator: example_string
            priority: example_string
            threshold: example_string
            time_function: example_string
        type:
          type: string
          example: standard
        value_function:
          type: string
          example: example_string
    ApplicationLinksResponse:
      type: object
      properties:
        servers:
          type: array
          items:
            type: integer
          example:
          - 100
        application_hosts:
          type: array
          items:
            type: integer
          example:
          - 100
        application_instances:
          type: array
          items:
            type: integer
          example:
          - 100
    EndUserSummaryResponse:
      type: object
      properties:
        apdex_score:
          type: number
          format: float
          example: 87.5
        apdex_target:
          type: number
          format: float
          example: 42.5
        response_time:
          type: number
          format: float
          example: 42.5
        throughput:
          type: number
          format: float
          example: 42.5
    UserDefinedConditionResponse:
      type: object
      properties:
        metric:
          type: string
          example: example_string
        value_function:
          type: string
          example: example_string
    DeploymentResponseType:
      type: object
      properties:
        changelog:
          type: string
          example: example_string
        description:
          type: string
          example: example_string
        id:
          type: integer
          example: 100
        links:
          $ref: '#/components/schemas/DeploymentLinksResponse'
        revision:
          type: string
          example: example_string
        timestamp:
          type: string
          format: date-time
          example: '2026-04-18T14:30:00Z'
        user:
          type: string
          example: example_string
    ConditionResponseType:
      type: object
      properties:
        condition_scope:
          type: string
          example: example_string
        enabled:
          type: boolean
          example: true
        entities:
          type: array
          items:
            type: integer
          example:
          - 100
        gc_metric:
          type: string
          example: example_string
        id:
          type: integer
          example: 100
        metric:
          type: string
          example: example_string
        name:
          type: string
          example: example-resource-01
        runbook_url:
          type: string
          example: https://portal.example.com/path/abc123
        terms:
          type: array
          items:
            $ref: '#/components/schemas/IJKTermsType'
          example:
          - duration: example_string
            operator: example_string
            priority: example_string
            threshold: example_string
            time_function: example_string
        type:
          type: string
          example: standard
        user_defined:
          $ref: '#/components/schemas/UserDefinedConditionResponse'
        violation_close_timer:
          type: integer
          example: 1718153645993
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: Api-Key
      description: New Relic License Key or Ingest API Key
externalDocs:
  description: New Relic Event API Documentation
  url: https://docs.newrelic.com/docs/data-apis/ingest-apis/event-api/introduction-event-api/
